---
#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

title: Shrikant Naidu
logo: /assets/images/s-logo.png # You can add own logo
description: # Add your awesome description
copyright:  © 2025 Shrikant Naidu. Powered by Jekyll & Designed by Themefisher

# Preloader
preloader: true # To disable preloader change value to false

menu:
  - name: Home
    url: /
  - name: Projects
    url: /Projects/
    submenu: 
      - name : Generative AI
        url : /generative-ai/
      - name : Deep Learning
        url : /deep-learning/
      - name : Data Engineering
        url : /data-engineering/

  - name: About
    url: /about/
  - name: Contact
    url: /contact/

# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ----------------------------------

layout_home_page: false # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: I'm a Data Scientist from Mumbai. I work with data to uncover insights and drive informed decision-making for businesses and organizations.
  hero-banner: /assets/images/sk-img-sharpened-new.png      # sk-banner.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: Shrikant Naidu

#-------------------------------
# Contact Info
contact:
  email: shrikantnaidu777@gmail.com
  phone: +91-8433888268  
  address:
    city: Mumbai
    street: 400089

# Contact Form
contact-form: example@email.com

# Social links
social:
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/shrikant-naidu/"}
  - { icon: "ti-github", link: "https://github.com/shrikantnaidu"}
  - { icon: "ti-twitter-alt", link: "https://x.com/shrikantnaiidu" }
  # - { icon: "ti-instagram", link: "https://www.instagram.com/sk.barcaholic/" }


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
userID: 
accessToken: 

#-------------------------------
# Google Analytics
google-analytics: G-MFM2R147R8 # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-archives

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# categories
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
